FROM node:12-alpine AS alpine

WORKDIR /usr/src/app

COPY package*.json .
COPY yarn.lock .
COPY tsconfig.json .
COPY ./backend ./backend

RUN yarn install

WORKDIR /usr/src/app/backend

RUN yarn tsc

CMD ["yarn", "start"]
