FROM node:12-alpine AS alpine

WORKDIR /usr/src/app

COPY package*.json .
COPY yarn.lock .
COPY tsconfig.json .
COPY ./frontend ./frontend

RUN yarn install

WORKDIR /usr/src/app/frontend

CMD ["yarn", "start"]
